name: Deploy to Prod

on:
  push:
    branches: [main]

jobs:
  build:
    name: Update
    runs-on: ubuntu-latest

    steps:
      - name: Pull Project
        uses: actions/checkout@v4.2.2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.7.1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Build and push
        uses: docker/build-push-action@v6.9.0
        with:
          context: .
          push: true
          tags: "ghcr.io/greg6775/traewellingmap:latest"
          cache-from: type=gha
          cache-to: type=gha,mode=max